import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;

/* this class has both utility and data function. the data is contained in SCENES and was generated by the utility
   function of this class. the utility function (genNewScenes) will take in a String that represents the number of
   parameters for each scenario (represented by the length of the string) along with the values that each parameter
   could contain (represented by the unique characters found in the string.

   it will then generate all possible permutations of the unique values in each parameter slot. the index of each
   resulting string represents what parameter it is for all scenarios.

   in our robot example, each parameter represents what we know about the west, east, north, south, and current squares.
   each of them can all contain one of three values: either be empty (.), have a can (c), or have a wall (w).

   as an example, the first scenario is represented as "wcccc" which means that in this scenario we are seeing a
   wall(w) to the west(0 idx), a can(c) to the east(1 idx), a can(c) to the north(2 idx), a can(c) to the south(3 idx)
   and a can(c) in the current location (4 idx)

   with 3 different possible values contained in 5 different parameters, we have a total of 3^9=243 possible scenarios
   the robot will find himself in. it should be noted that some scenarios are actually not possible. for example, any
   scenario that says there is a wall (w) at the current location (idx 4) is impossible since the system won't let the
   robot move into a wall. there are 3^4=81 different scenarios that have this condition and they could safely be removed
   without affecting the outcome. this is an optimization that is not necessary for 243 scenarios, but might be wise in
   applications with a larger number of parameters and/or possible values.

   another example would be for any map of functional size (i.e. 4x4 or greater), you would never have a scenario where
   there exists a wall to the north AND the south (3^3=27 scenarios) or to the east AND the west (3^3=27 scenarios).

   TODO: figure out the formula to calc how many can be removed 81+(27-9)+(27-9-2)=115
   TODO: try it with 9 param scenarios which includes knowledge of nw,sw,ne,se but not able to move there
   TODO: try it with 9 param scenarios which includes knowledge of nw,sw,ne,se but IS able to move there (four more actions)
   TODO: test to see what would happen if robot had knowledge of what square it came from
 */

public class Scenarios {
    // '.'=empty, 'c'=can, 'w'=wall
    // SCENES[][0]=west, SCENES[][1]=east, SCENES[][2]=north, SCENES[][3]=south, SCENES[][4]=current
    private static String[] SCENES = { "wcccc", "wwwww", "wc.c.", "w.ww.", "w.w.c", ".c..c", "ccwcc", "c..cc", ".ww..", "w.cc.", "c..w.", "c.wc.",
            "wwwwc", "..w..", "c..cw", ".c.w.", "wwcw.", "wcc..", "cwcww", "..c..", "cc..w", ".c..w", "...c.", "cw.wc", "cccw.", "ccc.w", "..ccc",
            "wcwww", ".wcw.", "cc..c", "wccc.", "..ccw", "ccwc.", "cw.ww", "ccww.", "w.w..", "c..wc", "wcc.c", "w.wcw", "wwccc", "..w.c", "wcwwc",
            "wc.cc", ".c.wc", ".cwww", ".c.cw", "wwccw", ".c.ww", "w.wcc", "cwc..", "...cw", "ccc.c", "c.w..", "wc.cw", "..c.c", ".wcwc", "wccww",
            "ccc..", "cccc.", "..cc.", "..c.w", ".cc.w", "cwwc.", "wcc.w", "w.w.w", "...cc", "ccwcw", "wccwc", "wccw.", "..cw.", "wcccw", ".wcww",
            "cc...", "wcww.", ".cc.c", "cwcc.", "wc..w", "cwc.w", "cww.c", "wc.w.", "c.w.w", "ww.cw", "...ww", "cwc.c", "cw.cc", "wwwc.", "c.w.c",
            "..cwc", ".cccc", "cw.cw", "c..ww", "ccccc", "c.cww", "www..", ".wcc.", ".cwwc", "wwwcc", "ccccw", "cww..", "wc..c", ".wc..", "c.cwc",
            ".cc..", "wwcwc", "..cww", "w..cc", "wc...", "cc.wc", ".w...", ".c...", ".wccc", "w.wwc", "wwwcw", "wwww.", "www.w", "cwcw.", "...w.",
            ".cwcc", "...wc", "cwcwc", ".wccw", "wwcww", ".wc.c", "c.ccw", ".w..c", ".ccc.", "c.cw.", ".cwcw", "w..cw", "cww.w", "www.c", "ww.cc",
            ".cww.", "cc.ww", "w.www", "cw.w.", ".w.ww", "w...c", "c.ccc", "c...w", "c.c.c", "ww.c.", ".wc.w", ".cw.w", "..wc.", "w..c.", ".cw.c",
            ".wwcc", "cc.w.", "....w", "cc.cw", "w.c..", "wc.ww", ".cwc.", "c.cc.", ".w.wc", "c.www", "ccw..", "c.c.w", "c...c", "....c", ".ccw.",
            "cc.cc", "wc.wc", ".ccwc", "ccw.w", "cwccc", "w..w.", "..wcc", "cwwwc", "w.cw.", "ww.wc", "w.cwc", "cwccw", "ccw.c", "ww.ww", "..wcw",
            "w...w", ".ccww", "cw...", ".cccw", ".wwc.", ".....", ".w..w", ".w.w.", "cwwww", "w.wc.", "cwww.", "cw.c.", ".wwww", "w..wc", "wcwcc",
            "wcw.w", "ww..w", "cwwcw", "wwcc.", "wcw.c", ".c.c.", "cc.c.", "wcwcw", "ww..c", "cwwcc", "w.cww", "w..ww", "wwc.c", "..ww.", ".c.cc",
            "wwc..", "cw..c", "ww.w.", ".w.c.", "..w.w", ".wwwc", "w.ccw", "cw..w", ".wwcw", ".www.", "cccwc", "c.wwc", "c.c..", "c....", "w....",
            "ww...", "c.wcc", "wcwc.", "wcw..", "c..c.", ".cw..", ".w.cc", "cccww", "..wwc", "w.c.c", "wwc.w", ".ww.w", "w.ccc", "ccwwc", "c.ww.",
            ".ww.c", "ccwww", ".w.cw", "..www", "c.wcw", "w.c.w"
    };
    static public Iterable<String> genNewScenes(String sceneParamVals) {
        HashSet<String> scenes = new HashSet<String>();
        char[] data = new char[sceneParamVals.length()];
        recurInclusivePermutation(sceneParamVals,data,sceneParamVals.length()-1, 0, scenes);
        return scenes;
    }
    //this method takes a set of characters found in str
    static private void recurInclusivePermutation(String str, char[] data, int last, int idx, Collection<String> scenes) {
        int i, len = str.length();
        for(i=0; i<len; i++) {
            data[idx] = str.charAt(i);
            if(idx==last){
                scenes.add(new String(data));
            } else {
                recurInclusivePermutation(str, data, last, idx+1, scenes);
            }
        }
    }
    static public Iterable<String> getScenes() {
        return Arrays.asList(SCENES);
    }
    static public int getNumberOfScenes() {
        return SCENES.length;
    }
    static public void main(String[] args) {
        Iterable<String> sc = genNewScenes(".......cw");
        int count=0;
        for( String s : sc) {
            System.out.print("\"" + s + "\", ");
            if( count++%10 == 9) {
                System.out.println();
            }
        }
        System.out.println();
        System.out.println("total: "+count);
    }
}